// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqjjuvgbekhmdxeuknpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxamp1dmdiZWtobWR4ZXVrbnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTQ5NjEsImV4cCI6MjA3MTQ3MDk2MX0.5LeSVA9MEisvZQhB9Mfddh9SW5wMETvPnLi1cJHsH1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});